# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 79a920fbf2c81a9df62ea011b06299d1c4bd1e2bc81042d6287f45a7b74aaa6f7956606d08738821e32ae18f247b2a91f18ac5b560c59ead68347b4acd7fed6c

test:
  secret_key_base: 0d949f32f3a553bb251d0f5a6687f3c6fe57e514c04452d1a6ff3d22865502b4980bbdc7bb7921c7eacc1f55e2d13a425e9611abea044c68ca7055045074dcb2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
